spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

app:
  date-format: yyyy-MM-dd HH:mm:ssX
  twelvedata-api-url: https://api.twelvedata.com
  twelvedata-api-key: ${TWELVEDATA_API_KEY}

currency-data-retriever:
  enabled: true
  cron-interval: 0 0 0 * * * 

logging:
  level:
    com:
      example:
        expensetrackerservice: debug
